export const REGIONS: Record<string, string[]> = {
  IT: [
    'Abruzzo',
    'Basilicata',
    'Calabria',
    'Campania',
    'Emilia-Romagna',
    'Friuli-Venezia Giulia',
    'Lazio',
    'Liguria',
    'Lombardia',
    'Marche',
    'Molise',
    'Piemonte',
    'Puglia',
    'Sardegna',
    'Sicilia',
    'Toscana',
    'Trentino-Alto Adige',
    'Umbria',
    "Valle d'Aosta",
    'Veneto',
  ],
  PT: [
    'Alentejo',
    'Algarve',
    'Centro',
    'Lisboa',
    'Norte',
    'Região Autónoma da Madeira',
    'Região Autónoma dos Açores',
  ],
};
